AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Data layer for ops-agent (S3, DynamoDB, SSM)

Parameters:
  ProjectName: { Type: String, Default: ops-agent }
  Stage: { Type: String, Default: prod }

Resources:
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Stage}-raw-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration: { Status: Enabled }

  VectorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Stage}-vectors-${AWS::AccountId}-${AWS::Region}"

  DocsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${Stage}-docs"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }

      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      GlobalSecondaryIndexes:
        - IndexName: Index-01
          KeySchema:
            - { AttributeName: SK, KeyType: HASH }
            - { AttributeName: PK, KeyType: RANGE }
          Projection:
            ProjectionType: ALL

  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${Stage}-settings"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - { AttributeName: PK, AttributeType: S }
        - { AttributeName: SK, AttributeType: S }

      KeySchema:
        - { AttributeName: PK, KeyType: HASH }
        - { AttributeName: SK, KeyType: RANGE }
      GlobalSecondaryIndexes:
        - IndexName: Index-01
          KeySchema:
            - { AttributeName: SK, KeyType: HASH }
            - { AttributeName: PK, KeyType: RANGE }
          Projection:
            ProjectionType: ALL


  # No SSM parameters are created in this stack; secrets are passed as template parameters to the app stack.

Outputs:
  RawBucketName:
    Value: !Ref RawBucket
    Export: { Name: !Sub "${ProjectName}-${Stage}-RawBucketName" }
  RawBucketArn:
    Value: !GetAtt RawBucket.Arn
    Export: { Name: !Sub "${ProjectName}-${Stage}-RawBucketArn" }
  VectorBucketName:
    Value: !Ref VectorBucket
    Export: { Name: !Sub "${ProjectName}-${Stage}-VectorBucketName" }
  VectorBucketArn:
    Value: !GetAtt VectorBucket.Arn
    Export: { Name: !Sub "${ProjectName}-${Stage}-VectorBucketArn" }
  DocsTableName:
    Value: !Ref DocsTable
    Export: { Name: !Sub "${ProjectName}-${Stage}-DocsTableName" }
  DocsTableArn:
    Value: !GetAtt DocsTable.Arn
    Export: { Name: !Sub "${ProjectName}-${Stage}-DocsTableArn" }
  SettingsTableName:
    Value: !Ref SettingsTable
    Export: { Name: !Sub "${ProjectName}-${Stage}-SettingsTableName" }
  SettingsTableArn:
    Value: !GetAtt SettingsTable.Arn
    Export: { Name: !Sub "${ProjectName}-${Stage}-SettingsTableArn" }
